version: '3.8'

services:
  web:
    build: .
    image: django-blog-app
    ports:
      - 8000:8000
    volumes:
    - /dev/shm:/dev/shm
    - .:/usr/src/app
    environment:
      - DJANGO_SECRET_KEY=secret
      - CHROMEDRIVER_PATH=/chromedriver/chromedriver
 