# Generated by Django 4.0.6 on 2022-07-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blog_image_url', models.URLField()),
                ('description', models.TextField()),
                ('reading_time', models.IntegerField()),
                ('author_name', models.CharField(max_length=50)),
                ('author_designation', models.CharField(max_length=100)),
                ('author_image_url', models.URLField()),
            ],
        ),
    ]
